name: Deploy Portfolio Locally

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish to local folder
        run: dotnet publish -c Release -o /var/www/portfolio

      - name: Restart site service (optional)
        run: sudo systemctl restart portfolio.service

