name: Deploy Portfolio Locally

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish to local folder
        run: dotnet publish -c Release -o /var/www/portfolio

      - name: Restart site service
        run: sudo systemctl restart portfolio.service
