name: Deploy Portfolio to Home Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o publish

      - name: Copy publish folder to server via SCP
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r publish/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/portfolio

      - name: Restart portfolio service on server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl restart my-po_
